name: 3-Sides-dev
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.6.2
  - libffi=3.4.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.12.4
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
